### ISSUE TITLE
diseñar el diagrama de modelos

### ISSUE THREAD

**Issue by jhonduarte79** [jhonduarte79/colcoders#4]

**Comment by GAMG-94** [comment]
![diagrama modelos](https://user-images.githubusercontent.com/63872158/197397739-17314e67-bed5-48cf-952c-b22c930ac5a5.jpg)

**Comment by GAMG-94** [comment]
Modelo Entidad Relación Actualizado

![WhatsApp Image 2022-10-23 at 5 05 28 PM](https://user-images.githubusercontent.com/63872158/197429463-275f4131-7d04-4545-91ae-95c16dc9192e.jpeg)
