### ISSUE TITLE
diseñar bosquejo de front end

### ISSUE THREAD

**Issue by jhonduarte79** [jhonduarte79/colcoders#5]

**Comment by GAMG-94** [comment]
![image](https://user-images.githubusercontent.com/63872158/197397502-a7328353-b475-4b4c-a677-403f81699815.png)


![image](https://user-images.githubusercontent.com/63872158/197397527-0b2246a1-41b6-4f3e-841e-4588d436653a.png)


![image](https://user-images.githubusercontent.com/63872158/197397544-582adbb8-e1ef-4409-8909-0003fb1d460c.png)


![image](https://user-images.githubusercontent.com/63872158/197397573-5ba089be-af09-4460-8f67-a028313a53a1.png)


![image](https://user-images.githubusercontent.com/63872158/197397605-9f28cdf2-850f-418f-b20a-b607478303b4.png)
